### ISSUE TITLE
ShouldBeEquivalentTo throws TargetInvocationException: Exception has been thrown by the target of an invocation with IPAddress

### ISSUE THREAD

**Issue by knguyen0928** [dennisdoomen/fluentassertions#134]
I found this in >= 2.2.0

Test:
```
void Main()
{
	var bar1 = new Bar {Address = IPAddress.Parse("1.2.3.4"), Word = "a"};
	var bar2 = new Bar {Address = IPAddress.Parse("1.2.3.4"), Word = "a"};
	bar1.ShouldBeEquivalentTo(bar2);
}

class Bar
{
	public IPAddress Address {get;set;}
	public string Word {get;set;}
}
```
Throws:
```
TargetInvocationException: Exception has been thrown by the target of an invocation.
```
Stacktrace:
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at FluentAssertions.Equivalency.EquivalencyValidationContext.CreateForNestedProperty(PropertyInfo nestedProperty, PropertyInfo matchingProperty) in z:\Builds\work\d21bade4fe20a99b\FluentAssertions.Core\Equivalency\EquivalencyValidationContext.cs:line 91
   at FluentAssertions.Equivalency.ComplexTypeEquivalencyStep.Handle(EquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in z:\Builds\work\d21bade4fe20a99b\FluentAssertions.Core\Equivalency\ComplexTypeEquivalencyStep.cs:line 48
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(EquivalencyValidationContext context) in z:\Builds\work\d21bade4fe20a99b\FluentAssertions.Core\Equivalency\EquivalencyValidator.cs:line 74
   at FluentAssertions.Equivalency.ComplexTypeEquivalencyStep.Handle(EquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in z:\Builds\work\d21bade4fe20a99b\FluentAssertions.Core\Equivalency\ComplexTypeEquivalencyStep.cs:line 48
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(EquivalencyValidationContext context) in z:\Builds\work\d21bade4fe20a99b\FluentAssertions.Core\Equivalency\EquivalencyValidator.cs:line 74
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in z:\Builds\work\d21bade4fe20a99b\FluentAssertions.Core\Equivalency\EquivalencyValidator.cs:line 55
   at FluentAssertions.AssertionExtensions.ShouldBeEquivalentTo[T](T subject, Object expectation, Func`2 config, String because, Object[] reasonArgs) in z:\Builds\work\d21bade4fe20a99b\FluentAssertions.Net40\AssertionExtensions.cs:line 519
   at FluentAssertions.AssertionExtensions.ShouldBeEquivalentTo[T](T subject, Object expectation, String because, Object[] reasonArgs) in z:\Builds\work\d21bade4fe20a99b\FluentAssertions.Net40\AssertionExtensions.cs:line 483
```

**Comment by dennisdoomen** [comment]
Introduced an API to change the rules for evaluating whether a type should be treated as having value semantics, either for a single structural equality comparison or globally. 
* The `EquivalencyOptionsBase` has received a new method `ComparingByValue` to specify a particular type. Obviously, this is also available through `AssertionOptions.AssertEquivalencyUsing`. 
* The `AssertionOptions` class has a new member `IsValueType` that you can use to change the predicate that enables value semantics.
