### ISSUE TITLE
Additional error from ShouldAllBeEquivalentTo for nested objects

### ISSUE THREAD

**Issue by shift-evgeny** [dennisdoomen/FluentAssertions#340]
In some cases when I compare arrays using ShouldAllBeEquivalentTo() and there is a difference it correctly reports that difference, but also reports an extra error.

The following unit tests reproduces the problem. (Can be added to Shared.Specs.)

```
using System.Collections.Generic;

#if !OLD_MSTEST
using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
#else
using Microsoft.VisualStudio.TestTools.UnitTesting;
#endif

namespace FluentAssertions.Specs
{
    [TestClass]
    public class BugTests
    {
        public class StringSubContainer
        {
            public string SubValue { get; set; }
        }

        public class StringContainer
        {
            public StringContainer(string mainValue, string subValue = null)
            {
                MainValue = mainValue;
                SubValues = new[]
                {
                    new StringSubContainer
                    {
                        SubValue = subValue
                    }
                };
            }

            public string MainValue { get; set; }
            public IList<StringSubContainer> SubValues { get; set; }
        }

        public class MyClass
        {
            public StringContainer One { get; set; }
            public StringContainer Two { get; set; }
        }

        [TestMethod]
        public void TestWrongError5()
        {
            var expected = new[]
            {
                new MyClass
                {
                    One = new StringContainer("EXPECTED", "EXPECTED"),
                    Two = new StringContainer("CORRECT"),
                },
                new MyClass()
            };

            var actual = new[]
            {
                new MyClass
                {
                    One = new StringContainer("INCORRECT", "INCORRECT"),
                    Two = new StringContainer("CORRECT"),
                },
                new MyClass()
            };

            actual.ShouldAllBeEquivalentTo(expected);
        }
    }
}
```

Output:

```
Expected item[0].One to be 

FluentAssertions.Specs.BugTests+StringContainer
{
   MainValue = "EXPECTED"
   SubValues = {FluentAssertions.Specs.BugTests+StringSubContainer
   {
      SubValue = "EXPECTED"
   }}
}, but found <null>.

Expected item[0].Two to be 

FluentAssertions.Specs.BugTests+StringContainer
{
   MainValue = "CORRECT"
   SubValues = {FluentAssertions.Specs.BugTests+StringSubContainer
   {
      SubValue = <null>
   }}
}, but found <null>.

With configuration:
- Use declared types and members
- Compare enums by value
- Include all non-private properties
- Include all non-private fields
- Match member by name (or throw)
- Be strict about the order of items in byte arrays

   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in LateBoundTestFramework.cs: line 31
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in TestFrameworkProvider.cs: line 42
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context) in CollectingAssertionStrategy.cs: line 50
   at FluentAssertions.Execution.AssertionScope.Dispose() in AssertionScope.cs: line 252
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in EquivalencyValidator.cs: line 37
   at FluentAssertions.AssertionExtensions.ShouldAllBeEquivalentTo(IEnumerable`1 subject, IEnumerable expectation, Func`2 config, String because, Object[] reasonArgs) in AssertionExtensions.cs: line 548
   at FluentAssertions.AssertionExtensions.ShouldAllBeEquivalentTo(IEnumerable`1 subject, IEnumerable expectation, String because, Object[] reasonArgs) in AssertionExtensions.cs: line 506
   at FluentAssertions.Specs.BugTests.TestWrongError5() in BugTests.cs: line 67
```

Property "One" actually differs, but property "Two" is equal between the two objects, yet an error is reported about "Two" as well. Note that the error about property "One" is also incorrect: it says "found <null>" when the expected value is not null. It seems to be getting something confused between the two objects in the arrays.

**Comment by dennisdoomen** [comment]
Interesting bug. Will need to dive into that.

**Comment by dennisdoomen** [comment]
Did a bit of investigation and concluded that the error reported by FA is correct. By default, FA will ignore the order of items in collections and arrays. So since you have two items in both arrays, FA will compare each combination and try to find an exact match. If that doesn't exist, it will try to find the closest match (that is, the one with the least amount of errors).

**Comment by shift-evgeny** [comment]
I would still encourage you to change it to a more helpful error. It may be "correct" in the strict sense that "it can be shown by careful analysis that the error does not contradict the design", but it certainly is not useful to the user. Even you, the person who wrote the code, thought it was a bug before you investigated it!

**Comment by dennisdoomen** [comment]
Good point. I will see how we can improve the error.

**Comment by shift-evgeny** [comment]
Thanks for fixing this. However, if you just add this property to the `StringContainer` class
```public string FirstSubValue => SubValues?.FirstOrDefault()?.SubValue;```

then the error is wrong again:
```
Expected item[0].One to be 

FluentAssertions.Specs.BasicEquivalencySpecs+StringContainer
{
   FirstSubValue = "EXPECTED"
   MainValue = "EXPECTED"
   SubValues = {FluentAssertions.Specs.BasicEquivalencySpecs+StringSubContainer
   {
      SubValue = "EXPECTED"
   }}
}, but found <null>.
Expected item[0].Two to be 

FluentAssertions.Specs.BasicEquivalencySpecs+StringContainer
{
   FirstSubValue = <null>
   MainValue = "CORRECT"
   SubValues = {FluentAssertions.Specs.BasicEquivalencySpecs+StringSubContainer
   {
      SubValue = <null>
   }}
}, but found <null>.

With configuration:
- Use declared types and members
- Compare enums by value
- Include all non-private properties
- Include all non-private fields
- Match member by name (or throw)
- Be strict about the order of items in byte arrays

   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in C:\G it\fluentassertions\Src\Shared\Execution\LateBoundTestFramework.cs:line 31
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\G it\fluentassertions\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context) in C:\G it\fluentassertions\Src\Core\Execution\CollectingAssertionStrategy.cs:line 50
   at FluentAssertions.Execution.AssertionScope.Dispose() in C:\G it\fluentassertions\Src\Core\Execution\AssertionScope.cs:line 252
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\G it\fluentassertions\Src\Core\Equivalency\EquivalencyValidator.cs:line 41
   at FluentAssertions.AssertionExtensions.ShouldAllBeEquivalentTo[T](IEnumerable`1 subject, IEnumerable expectation, Func`2 config, String because, Object[] becauseArgs) in C:\G it\fluentassertions\Src\Shared\AssertionExtensions.cs:line 680
   at FluentAssertions.AssertionExtensions.ShouldAllBeEquivalentTo[T](IEnumerable`1 subject, IEnumerable expectation, String because, Object[] becauseArgs) in C:\G it\fluentassertions\Src\Shared\AssertionExtensions.cs:line 637
   at FluentAssertions.Specs.BasicEquivalencySpecs.<>c__DisplayClass97_0.<When_deeply_nested_strings_dont_match_it_should_properly_report_the_mismatches>b__0() in C:\G it\fluentassertions\Tests\FluentAssertions.Shared.Specs\BasicEquivalencySpecs.cs:line 2575
   at FluentAssertions.Specs.BasicEquivalencySpecs.When_deeply_nested_strings_dont_match_it_should_properly_report_the_mismatches() in C:\G it\fluentassertions\Tests\FluentAssertions.Shared.Specs\BasicEquivalencySpecs.cs:line 2576
```
