### ISSUE TITLE
string.Should().Be(): Input format is not in a correct format with DateTime and brackets

### ISSUE THREAD

**Issue by cknaap** [dennisdoomen/FluentAssertions#465]
Hello Dennis,

Happily using FluentAssertions (thanks!), comparing JSON strings I came across a cornercase.

.Net Core 1.0.0
XUnit 2.1.0
FluentAssertions 4.13.0

        [Fact]
        public void ProofIssue()
        {
            string result = "{ a : [{ b : \"2016-05-23T10:45:12Z\" } ]}";

            string expectedJson = "{ a : [{ b : \"2016-05-23T10:45:12Z\" }] }";
            //Strings differ in the last 3 characters.

            result.Should().Be(expectedJson);
        }

This results in an exception: 

Test Name:	Spark.IndexRepository.MongoDB.Tests.IndexEntrySerializationTests.TestDT3
Test FullName:	Spark.IndexRepository.MongoDB.Tests.IndexEntrySerializationTests.TestDT3
Test Source:	C:\projects\fhir\source\spark.pluggable\test\Spark.IndexRepository.MongoDB.Tests\IndexEntrySerializationTests.cs : line 249
Test Outcome:	Failed
Test Duration:	0:00:00,049

Result StackTrace:	
at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at FluentAssertions.Execution.MessageBuilder.FormatArgumentPlaceholders(String failureMessage, Object[] failureArgs)
   at FluentAssertions.Execution.MessageBuilder.Build(String message, Object[] messageArgs, String reason, ContextDataItems contextData)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstMismatch()
   at FluentAssertions.Primitives.StringValidator.Validate()
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs)
   at <your test method>
Result Message:	Input string was not in a correct format.

Based on a few experiments I think It is related to the combination of square brackets and datetime literal in the string, but I don't know how it arrives at String.Format(), where the exception occurs.

**Comment by dennisdoomen** [comment]
Thanks for reporting this.
